### ISSUE TITLE
Automatically check correctness of tool package information

### ISSUE THREAD

**Issue by akahles** [icgc-argo/wfpm#37]
It would be helpful if during tool package testing the correctness of the package information in `pkg.json` could already be checked. 

## Detailed Description
When generating the tool template with the `new tool` command, the `pkg.json` is filled with the appropriate information. However, some of the information can become inconsistent through changes the user applies during package development. For instance, it is assumed in `pkg.json` that the "main" property is "main.nf", which is not necessarily the case.  Unfortunately, if this is not checked, a mismatch will only turn out to be problematic once the package is included as a dependency when generating a new workflow. Before that, this information is not used and all tests pass.

**Comment by junjun-zhang** [comment]
Thanks @akahles for your feedback. This is definitely on our TODO list, with your feedback, will give this a proriority.

**Comment by junjun-zhang** [comment]
We will perform a few integrity check when running `wfpm test`:
- pkg_name, package name matches name of the containing folder
- main, package main points to workflow script that exists
- version, package version matches what's in the main and checker scripts

**Comment by junjun-zhang** [comment]
addressed by #44
